[package]
name = "forge"
version = "0.1.0"
authors = ["ambrozic <ambrozic@gmail.com>"]

[dependencies]
ansi_term = "0.9.0"
ssh2 = "0.3.1"
yaml-rust = {version = "0.3.5", features = ["preserve_order"]}
clap = "2.20.1"
